[theme]
primaryColor = "#D4AF37"
backgroundColor = "#070D1D"
secondaryBackgroundColor = "#0D152B"
textColor = "#F1F5F9"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
