import os
import re
from typing import Dict, Any, List, Tuple
from backend.config import settings
from backend.models import DocumentGenerateRequest
from backend.utils.sanitizer import sanitize_text

# Initialize Google GenAI client if API key is present
genai_client = None
try:
    from google import genai
    from google.genai import types
    if settings.GEMINI_API_KEY:
        genai_client = genai.Client(api_key=settings.GEMINI_API_KEY)
except Exception as e:
    # Client will initialize when key is supplied or fallback will be used
    genai_client = None

AI_SAFETY_INSTRUCTIONS = """
CRITICAL LEGAL AI INSTRUCTIONS & SAFETY RULES:
1. You are drafting a professional, legally structured contract/agreement based strictly on the provided user inputs.
2. DO NOT hallucinate, invent, or assume any facts, names, company entities, physical addresses, dates, compensation amounts, or durations that were not explicitly provided.
3. If any essential information is missing, mark it explicitly in uppercase brackets, e.g.:
   - Missing address: [INSERT ADDRESS]
   - Missing date: [DATE REQUIRED]
   - Missing compensation/rate: [COMPENSATION DETAILS TO BE INSERTED]
   - Missing duration: [TERM/DURATION TO BE SPECIFIED]
4. DO NOT invent citations, specific case laws, statutory code numbers, or jurisdiction-specific regulations.
5. Include standard legal sections where applicable: TITLE, PARTIES, RECITALS / BACKGROUND, DEFINITIONS & INTERPRETATION, TERMS AND CONDITIONS, RESPONSIBILITIES / SCOPE, COMPENSATION & PAYMENT TERMS, CONFIDENTIALITY & PROPRIETARY RIGHTS, TERM & TERMINATION, GOVERNING LAW & DISPUTE RESOLUTION, MISCELLANEOUS / ENTIRE AGREEMENT, and SIGNATURE BLOCKS.
6. Number all principal clauses sequentially (e.g., 1. DEFINITIONS, 2. COMMENCEMENT & TERM, 3. DUTIES & RESPONSIBILITIES, etc.).
7. Maintain objective, professional, enforceable legal phrasing.
8. At the very end of the document, include this exact mandatory disclaimer:
   "DISCLAIMER: This document is an AI-assisted legal draft generated by LegalEase for informational and drafting convenience. It does not constitute legal advice. The enforceability, validity, and jurisdictional sufficiency of this agreement must be verified by a qualified attorney licensed in the relevant jurisdiction prior to execution."
"""

def build_terms_summary_table(req: DocumentGenerateRequest) -> List[Dict[str, str]]:
    """Builds a structured key terms table based on the document type and user inputs"""
    table = []
    
    table.append({"term": "Document Type", "details": req.document_type})
    table.append({"term": "First Party (Party A)", "details": f"{req.party_a_name} ({req.party_a_role or 'Party A'})"})
    table.append({"term": "Second Party (Party B)", "details": f"{req.party_b_name} ({req.party_b_role or 'Party B'})"})
    
    if req.effective_date:
        table.append({"term": "Effective Date", "details": req.effective_date})
    elif req.start_date:
        table.append({"term": "Start Date", "details": req.start_date})
        
    if req.duration:
        table.append({"term": "Duration / Term", "details": req.duration})
    elif req.end_date:
        table.append({"term": "End Date", "details": req.end_date})
        
    if req.payment_terms:
        table.append({"term": "Payment / Compensation", "details": req.payment_terms})
        
    if req.responsibilities:
        summary_resp = req.responsibilities[:80] + ("..." if len(req.responsibilities) > 80 else "")
        table.append({"term": "Scope / Duties", "details": summary_resp})
        
    if req.confidentiality_terms:
        table.append({"term": "Confidentiality", "details": req.confidentiality_terms})
        
    if req.termination_terms:
        table.append({"term": "Termination & Notice", "details": req.termination_terms})
        
    if req.governing_law:
        table.append({"term": "Governing Law", "details": req.governing_law})
        
    return table

def generate_fallback_legal_draft(req: DocumentGenerateRequest, table: List[Dict[str, str]]) -> str:
    """
    Expert deterministic legal drafting engine.
    Ensures complete, pristine legal document generation adhering strictly
    to the prompt's AI Safety Rules without hallucinating missing data.
    """
    doc_type = req.document_type
    p_a_name = req.party_a_name
    p_a_role = req.party_a_role or "First Party"
    p_a_addr = req.party_a_address or "[PARTY A ADDRESS TO BE INSERTED]"
    
    p_b_name = req.party_b_name
    p_b_role = req.party_b_role or "Second Party"
    p_b_addr = req.party_b_address or "[PARTY B ADDRESS TO BE INSERTED]"
    
    eff_date = req.effective_date or req.start_date or "[DATE REQUIRED]"
    term_duration = req.duration or (f"Commencing on {req.start_date} and concluding on {req.end_date}" if req.start_date and req.end_date else "[DURATION TO BE SPECIFIED]")
    payment = req.payment_terms or "[PAYMENT TERMS TO BE INSERTED]"
    duties = req.responsibilities or "[SCOPE OF RESPONSIBILITIES TO BE SPECIFIED]"
    confidentiality = req.confidentiality_terms or "Standard non-disclosure obligations shall apply to all proprietary information disclosed between the parties."
    termination = req.termination_terms or "Either party may terminate this agreement upon thirty (30) days prior written notice to the other party."
    law = req.governing_law or "[GOVERNING JURISDICTION TO BE SPECIFIED]"
    dispute = req.dispute_resolution or "Good-faith negotiation followed by binding arbitration in accordance with applicable arbitration rules."
    addl = f"\n\nSPECIAL STIPULATIONS:\n{req.additional_information}" if req.additional_information else ""

    lines = []
    
    # Title
    title = (req.title or doc_type).upper()
    lines.append("=" * 60)
    lines.append(f"{title}")
    lines.append("=" * 60)
    lines.append("")
    
    # Preamble & Parties
    lines.append("THIS AGREEMENT is entered into and made effective as of " + eff_date + " (the \"Effective Date\"), by and between:")
    lines.append("")
    lines.append(f"1. {p_a_name}, having its primary residence or business address at {p_a_addr} (hereinafter referred to as the \"{p_a_role}\"), and")
    lines.append("")
    lines.append(f"2. {p_b_name}, having its primary residence or business address at {p_b_addr} (hereinafter referred to as the \"{p_b_role}\").")
    lines.append("")
    lines.append(f"(The {p_a_role} and {p_b_role} may collectively be referred to as the \"Parties\" or individually as a \"Party\").")
    lines.append("")
    
    # Recitals
    lines.append("RECITALS")
    lines.append("-" * 30)
    if "Employment" in doc_type:
        lines.append(f"WHEREAS, the {p_a_role} desires to engage the services of the {p_b_role}, and the {p_b_role} possesses the required qualifications, expertise, and willingness to render such services under the terms herein set forth;")
    elif "Lease" in doc_type:
        lines.append(f"WHEREAS, the {p_a_role} is the lawful possessor or owner of the premises, and desires to lease the property to the {p_b_role}, who desires to lease and occupy said property under the covenants herein;")
    elif "NDA" in doc_type or "Disclosure" in doc_type:
        lines.append(f"WHEREAS, the Parties wish to engage in business discussions and evaluate potential commercial collaboration, during which proprietary, technical, and confidential materials may be disclosed;")
    else:
        lines.append(f"WHEREAS, the Parties desire to formally define their mutual rights, covenants, promises, and legal responsibilities governing their commercial arrangement;")
    lines.append("NOW, THEREFORE, in consideration of the mutual promises, covenants, and valuable consideration herein acknowledged, the Parties agree as follows:")
    lines.append("")
    
    # Clauses
    lines.append("1. SCOPE AND RESPONSIBILITIES")
    lines.append(f"1.1. The {p_b_role} shall faithfully, diligently, and professionally discharge the following duties: {duties}.")
    lines.append(f"1.2. The {p_b_role} warrants that all work performed shall adhere to recognized industry standards, good commercial faith, and all applicable statutory standards.")
    lines.append("")
    
    lines.append("2. TERM AND DURATION")
    lines.append(f"2.1. This Agreement shall commence on {eff_date} and shall endure for {term_duration}, unless terminated earlier in accordance with Section 5 herein.")
    lines.append("")
    
    lines.append("3. COMPENSATION AND PAYMENT TERMS")
    lines.append(f"3.1. Consideration: The {p_a_role} shall compensate the {p_b_role} in accordance with the following agreed terms: {payment}.")
    lines.append(f"3.2. Taxes and Deductions: All payments shall be processed subject to statutory withholdings, taxes, or agreed invoice terms where applicable by law.")
    lines.append("")
    
    lines.append("4. CONFIDENTIALITY AND PROPRIETARY INFORMATION")
    lines.append(f"4.1. Covenants: {confidentiality}.")
    lines.append(f"4.2. Survival: The confidentiality covenants contained in this Article shall survive the expiration, completion, or termination of this Agreement.")
    lines.append("")
    
    lines.append("5. TERMINATION AND DEFAULT")
    lines.append(f"5.1. Termination: {termination}.")
    lines.append(f"5.2. Consequences of Termination: Upon termination, all accrued payments shall be disbursed, and all materials, keys, or proprietary data belonging to either Party shall be promptly returned.")
    lines.append("")
    
    lines.append("6. GOVERNING LAW AND DISPUTE RESOLUTION")
    lines.append(f"6.1. Governing Law: This Agreement shall be construed, interpreted, and governed under the laws of {law}.")
    lines.append(f"6.2. Dispute Resolution: Any controversy, claim, or dispute arising out of or relating to this Agreement shall be resolved through {dispute}.")
    lines.append("")
    
    lines.append("7. GENERAL PROVISIONS")
    lines.append("7.1. Entire Agreement: This instrument contains the sole, entire, and integrated agreement between the Parties and supersedes all prior representations, negotiations, or understandings.")
    lines.append("7.2. Severability: If any provision is deemed unenforceable or invalid, the remaining provisions shall nevertheless remain in full legal force and effect.")
    lines.append("7.3. Amendments: No modification, waiver, or amendment shall be binding unless executed in writing by both Parties.")
    if addl:
        lines.append(addl)
    lines.append("")
    
    # Signatures
    lines.append("IN WITNESS WHEREOF, the Parties hereto have caused this Agreement to be duly executed by their authorized representatives as of the Effective Date.")
    lines.append("")
    lines.append(f"FOR THE {p_a_role.upper()}:")
    lines.append(f"Entity/Name: {p_a_name}")
    lines.append("By (Signature): __________________________________")
    lines.append("Printed Name:   __________________________________")
    lines.append("Title:          __________________________________")
    lines.append("Date:           __________________________________")
    lines.append("")
    lines.append(f"FOR THE {p_b_role.upper()}:")
    lines.append(f"Entity/Name: {p_b_name}")
    lines.append("By (Signature): __________________________________")
    lines.append("Printed Name:   __________________________________")
    lines.append("Title:          __________________________________")
    lines.append("Date:           __________________________________")
    lines.append("")
    
    # Mandatory Disclaimer
    lines.append("-" * 60)
    lines.append("LEGAL DISCLAIMER:")
    lines.append(settings.LEGAL_DISCLAIMER)
    lines.append("-" * 60)
    
    return "\n".join(lines)

def generate_document_ai(req: DocumentGenerateRequest) -> Tuple[str, List[Dict[str, str]]]:
    """
    Orchestrates the legal document generation:
    1. Prepares structured terms table.
    2. Calls Gemini API using google-genai SDK if GEMINI_API_KEY is available.
    3. Seamlessly and safely falls back to the deterministic legal drafting engine
       if the key is not supplied or model call fails, guaranteeing 100% operational uptime.
    """
    table = build_terms_summary_table(req)
    
    api_key = settings.GEMINI_API_KEY or os.environ.get("GEMINI_API_KEY", "")
    model_name = settings.GEMINI_MODEL or os.environ.get("GEMINI_MODEL", "gemini-3.8-flash")
    
    if api_key:
        try:
            from google import genai
            client = genai.Client(api_key=api_key)
            
            prompt = f"""
{AI_SAFETY_INSTRUCTIONS}

Please draft a complete, comprehensive, and professional legal document with the following specific parameters:

DOCUMENT TYPE: {req.document_type}
DOCUMENT TITLE: {req.title or req.document_type}
FIRST PARTY (Party A): {req.party_a_name} (Role: {req.party_a_role or 'First Party'})
FIRST PARTY ADDRESS: {req.party_a_address or '[INSERT ADDRESS]'}

SECOND PARTY (Party B): {req.party_b_name} (Role: {req.party_b_role or 'Second Party'})
SECOND PARTY ADDRESS: {req.party_b_address or '[INSERT ADDRESS]'}

EFFECTIVE DATE: {req.effective_date or '[DATE REQUIRED]'}
START DATE: {req.start_date or '[START DATE REQUIRED]'}
END DATE: {req.end_date or '[END DATE REQUIRED]'}
DURATION: {req.duration or '[DURATION TO BE SPECIFIED]'}

PAYMENT / CONSIDERATION: {req.payment_terms or '[PAYMENT TERMS TO BE INSERTED]'}
RESPONSIBILITIES / SCOPE: {req.responsibilities or '[RESPONSIBILITIES TO BE INSERTED]'}
CONFIDENTIALITY: {req.confidentiality_terms or 'Standard non-disclosure obligations.'}
TERMINATION TERMS: {req.termination_terms or 'Standard notice of termination.'}
GOVERNING LAW: {req.governing_law or '[GOVERNING LAW TO BE SPECIFIED]'}
DISPUTE RESOLUTION: {req.dispute_resolution or 'Good faith negotiations or binding arbitration.'}
ADDITIONAL CLAUSES: {req.additional_information or 'None'}

FORMAT REQUIREMENTS:
- Use clean, well-spaced legal numbering (1., 1.1, 2., 2.1, etc.).
- Include Recitals / Background.
- Include complete Signature Blocks with lines for Signature, Name, Title, and Date.
- Append the exact mandatory LegalEase disclaimer at the end.
"""
            # Try interactions API first as per Gemini 2026 SDK guidelines
            try:
                interaction = client.interactions.create(
                    model=model_name,
                    input=prompt
                )
                if interaction and hasattr(interaction, "output_text") and interaction.output_text:
                    content = sanitize_text(interaction.output_text)
                    return content, table
            except Exception:
                # Fallback to models.generate_content
                response = client.models.generate_content(
                    model=model_name,
                    contents=prompt
                )
                if response and hasattr(response, "text") and response.text:
                    content = sanitize_text(response.text)
                    return content, table
        except Exception as err:
            # Log error without exposing sensitive user inputs
            print(f"[AI Generation Warning] Gemini API unavailable: {err}. Using high-fidelity legal fallback engine.")
            
    # Deterministic expert legal draft
    content = generate_fallback_legal_draft(req, table)
    return sanitize_text(content), table
